### ISSUE TITLE
Mulighed for at hente afhentningssteds ID?

### ISSUE THREAD

**Issue by boutzamat** [Repox/GLS-Pakkeshop-Webservice-PHP-API#1]
Fedt API du har udviklet - hatten af for det! :+1: 
-Vil dog lige høre om du har planer om at integrere ID for afhentingsstedet?
Nogen virksomheder der tilbyder labels, forlanger et ID på afhentningsstedet.

Igen, rigtig flot arbejde du har lavet.

**Comment by Repox** [comment]
Jeg er glad for at du kan bruge det :)

Umiddelbart har alle shop-instanser et felt der hedder Number (og kan i eksemplerne tilgås via $shop->Number) - er det ikke det ID du leder efter?

**Comment by boutzamat** [comment]
Det kan jeg bestemt! :)

Det var da lige præcis det jeg ledte efter - du er konge!

**Comment by Repox** [comment]
Super :-) Du må sige til hvis du skal bruge andet :-)

**Comment by boutzamat** [comment]
Vil jeg gøre, tusind tak for venligheden Dan :) 

PS: Følger dig lige, du har sku gang i nogen spændende ting :D
